// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://efigztrbarvxhszyqfgd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVmaWd6dHJiYXJ2eGhzenlxZmdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MTgwMDUsImV4cCI6MjA2MjI5NDAwNX0.hMkg0HLYk7pnqQY_IAP5thJeptQawNebdW2h81WlKs0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);